const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {Window}=require('happy-dom');
(async()=>{
 const window=new Window({url:'https://daleel.test/Pages/home.html'});window.document.body.innerHTML='<header id="header"></header><main id="main"></main><nav id="bottomNav"></nav><footer id="footer"></footer><div id="toast"></div>';
 const calls=[],records={};let callback;
 const timestamp=n=>({toMillis:()=>n,toDate:()=>new Date(n)});const now=Date.now();
 const fakeUser={uid:'alice',email:'alice@example.com',displayName:'Alice Actual',emailVerified:true,reload:async()=>{},getIdToken:async()=>{}};
 const fakeProfile={uid:'alice',email:fakeUser.email,fullName:'Alice Actual',travelMood:'adventure',onboardingCompleted:true};
 const exp={id:'exp',hostUid:'host',titleAr:'جولة محلية',titleEn:'Local walking tour',descriptionAr:'تفاصيل تجربة محلية فعلية طويلة مع تعليمات السلامة.',descriptionEn:'Actual local experience with safety and meeting instructions.',placeId:'petra',regionId:'maan',category:'tour',status:'approved',priceCents:2500,duration:60,communityBps:1000};
 const slot={...exp,id:'slot',experienceId:'exp',capacity:6,booked:0,open:true,startAt:timestamp(now+96*3600000),endAt:timestamp(now+97*3600000)};
 const booking={id:'alice_slot',...slot,uid:'alice',slotId:'slot',guests:1,totalCents:2500,communityCents:250,hostCents:2250,status:'confirmed',hostPaid:true,travelerPaid:true,travelerName:'Alice',startAt:timestamp(now-3*3600000),endAt:timestamp(now-2*3600000)};
 const trip={id:'trip',uid:'alice',name:'Actual trip',startDate:'2026-12-10',days:3,status:'planned',stops:[{id:'stop1',placeId:'petra',day:0,time:'09:00',duration:180},{id:'stop2',placeId:'rum',day:0,time:'09:30',duration:120}]};
 const h={id:'host',uid:'host',fullName:'Reviewed Host',bio:'Local host with a privately reviewed identity.',verified:true,publicPhone:''};
 const fixtures={users:[fakeProfile],hosts:[h],hostApplications:[],experiences:[exp],slots:[slot],trips:[trip],bookings:[booking,{...booking,id:'alice_slot2'}],reviews:[],goals:[],contributions:[]};
 const D={read:async(kind,id)=>fixtures[kind]?.find(x=>x.id===id||x.uid===id)||null,list:async(kind,filters=[])=>fixtures[kind]?.filter(x=>filters.every(([k,v])=>x[k]===v))||[],save:async(...args)=>calls.push(['save',...args]),create:async(...args)=>{calls.push(['create',...args]);return{id:'created'};},serverTimestamp:()=>now,reserve:async o=>calls.push(['reserve',o]),cancelBooking:async(...a)=>calls.push(['cancel',...a]),confirmCash:async(...a)=>calls.push(['cash',...a]),reviewBooking:async(...a)=>calls.push(['review',...a]),publishSlots:async(...a)=>calls.push(['slots',...a])};
 const context=vm.createContext({document:window.document,window,location:{pathname:'/Pages/home.html',search:'',origin:'https://daleel.test',assign:u=>calls.push(['navigate',u]),reload:()=>calls.push(['reload'])},localStorage:window.localStorage,FormData:window.FormData,URL,URLSearchParams,Blob,crypto:require('node:crypto').webcrypto,console,setTimeout:()=>0,clearTimeout:()=>{},navigator:window.navigator,auth:{currentUser:fakeUser},db:{},D,onAuthStateChanged:(a,c)=>{callback=c;},signOut:async()=>calls.push(['signOut']),updateProfile:async(u,o)=>{Object.assign(u,{displayName:o.displayName});calls.push(['updateProfile',o]);},createUserWithEmailAndPassword:async(a,email,password)=>{calls.push(['signup',email]);return{user:{...fakeUser,email}};},sendPasswordResetEmail:async(a,email)=>calls.push(['reset',email]),sendEmailVerification:async()=>calls.push(['verify']),browserLocalPersistence:'local',setPersistence:async()=>{},signInWithEmailAndPassword:async(a,email)=>calls.push(['signin',email])});
 window.confirm=()=>true;window.open=u=>calls.push(['open',u]);
 let source=fs.readFileSync('JS/app/content.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('JS/app/catalog.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('JS/app/app.js','utf8').replace(/^import[\s\S]*?;\s*/gm,'');vm.runInContext(source,context);context.testUser=fakeUser;context.testProfile=fakeProfile;
 vm.runInContext('user=testUser;profile=testProfile;',context);
 let checks=0;const run=s=>vm.runInContext(s,context);
 async function render(v,p={}){context.testView=v;context.testParams=p;run("view=testView;params.forEach((_,k)=>params.delete(k));Object.entries(testParams).forEach(([k,v])=>params.set(k,v));");await run('render()');assert(!window.document.querySelector('#main').textContent.includes('Could not load'),'render '+v);assert(!window.document.querySelector('#main').textContent.includes('تعذّر تحميل الصفحة'),'render '+v);checks++;}
 for(const language of ['ar','en']){context.testLang=language;run('lang=testLang');for(const v of ['landing','home','explore','experiences','trips','impact','goals','profile','login','register','mood','onboarding','hostDashboard','policy'])await render(v);await render('place',{id:'petra'});await render('experience',{id:'exp'});await render('host',{id:'host'});await render('booking',{id:'slot'});await render('builder',{id:'trip'});assert(window.document.querySelector('#tripSummary').textContent.includes(language==='ar'?'تعارض':'conflict'));checks++;}
 // Mood personalization changes actual recommendations.
 run("profile.travelMood='adventure'");await render('home');const adventure=[...window.document.querySelectorAll('.card h3')].map(n=>n.textContent).join();run("profile.travelMood='food'");await render('home');const food=[...window.document.querySelectorAll('.card h3')].map(n=>n.textContent).join();assert.notEqual(adventure,food);checks++;
 await render('trips');assert.equal(window.document.querySelectorAll('[data-action=openReview]').length,2,'second booking must remain traveler view');checks++;
 await render('builder',{id:'trip'});window.document.querySelector('[data-action=moveStop][data-dir="1"]').click();await new Promise(r=>setImmediate(r));assert.equal(run('currentTrip.stops[0].placeId'),'rum');checks++;
 window.document.querySelector('[data-action=saveTrip]').click();await new Promise(r=>setImmediate(r));assert(calls.some(c=>c[0]==='save'&&c[1]==='trips'));checks++;
 await render('booking',{id:'slot'});const f=window.document.querySelector('#bookingForm');f.querySelector('[name=guests]').value='2';f.querySelector('[name=agree]').checked=true;f.dispatchEvent(new window.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert(calls.some(c=>c[0]==='reserve'&&c[1].slotId==='slot'&&c[1].guests===2));checks++;
 await render('register');const auth=window.document.querySelector('#authForm');auth.querySelector('[name=name]').value='Alice Test';auth.querySelector('[name=email]').value='fresh@example.com';auth.querySelector('[name=password]').value='QaPassword123';auth.querySelector('[name=agree]').checked=true;auth.dispatchEvent(new window.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));const signup=calls.findIndex(c=>c[0]==='signup'),logout=calls.findIndex((c,i)=>i>signup&&c[0]==='signOut'),nav=calls.findIndex((c,i)=>i>logout&&c[0]==='navigate'&&c[1].includes('login.html?registered=1'));assert(signup>=0&&logout>signup&&nav>logout);checks++;

 await render('goals');assert.equal(window.document.querySelectorAll('.section .grid .panel').length,5);checks++;
 await render('experiences');assert.equal(window.document.querySelectorAll('.section .grid .panel').length,10);checks++;
 await render('explore',{region:'mafraq'});assert.equal(window.document.querySelectorAll('#placesGrid .card').length,1);checks++;
 await render('trips');window.document.querySelector('[data-action=tripState][data-status=current]').click();await new Promise(r=>setImmediate(r));assert(calls.at(-1)[1].includes('status=current'));checks++;
 await render('trips');const newTrip=window.document.querySelector('#newTrip');newTrip.hidden=false;newTrip.querySelector('[name=name]').value='My saved trip';newTrip.dispatchEvent(new window.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert(calls.at(-1)[1].includes('itinerary.html?status=planned&highlight=created'));checks++;
 context.hostUser={...fakeUser,uid:'host'};run('user=hostUser');await render('hostDashboard');assert(window.document.querySelector('[data-slots=exp]'));checks++;
 context.adminUser={...fakeUser,uid:'admin',email:'hamzaalfarraj16@gmail.com'};run('user=adminUser');await render('admin');assert(window.document.querySelector('#goalForm'));checks++;
 run('user=null');await render('profile');assert(calls.at(-1)[1].includes('login.html?next=profile'));checks++;
 // Every internal route and catalog image exists, every route renders with both languages.
 for(const filename of fs.readdirSync('Pages').filter(x=>x.endsWith('.html'))){const html=fs.readFileSync('Pages/'+filename,'utf8');assert(html.includes('/css/app.css')&&html.includes('/JS/app/app.js'));checks++;}
 const catalog=run('places');for(const p of catalog){assert(fs.existsSync('assets/images/'+p.image),p.image);checks++;}
 console.log(`PASS ${checks} bilingual rendering, forms, navigation, mood, trip, booking and registration checks (DOM simulation; not a deployed browser test)`);await window.happyDOM.abort();
})().catch(err=>{console.error(err);process.exitCode=1;});
