const {readFileSync}=require('node:fs');
const assert=require('node:assert/strict');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,getDocs,updateDoc,collection,query,where,runTransaction,serverTimestamp,Timestamp,writeBatch}=require('firebase/firestore');
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-daleel',firestore:{host:'127.0.0.1',port:8085,rules:readFileSync('firestore.rules','utf8')}});await env.clearFirestore();
 const db=(uid,extra={})=>env.authenticatedContext(uid,{email:uid+'@example.com',email_verified:true,...extra}).firestore();
 const alice=db('alice'),bob=db('bob'),host=db('host'),admin=db('admin',{email:'hamzaalfarraj16@gmail.com'}),imposter=db('imposter',{email:'hamzaalfarraj16@gmail.com',email_verified:false}),anon=env.unauthenticatedContext().firestore();
 let checks=0;async function yes(p){await assertSucceeds(p);checks++;}async function no(p){await assertFails(p);checks++;}
 const jpg='data:image/jpeg;base64,'+'A'.repeat(100);
 const app={uid:'host',fullName:'Real Host',bio:'Host identity and local experience description for private review.',phone:'+962700000000',regionId:'maan',photoData:'',identityData:jpg,publishPhone:false,status:'pending',reviewNote:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};
 await yes(setDoc(doc(host,'hostApplications','host'),app));await no(getDoc(doc(alice,'hostApplications','host')));await no(getDoc(doc(anon,'hostApplications','host')));await no(updateDoc(doc(host,'hostApplications','host'),{status:'approved',updatedAt:serverTimestamp()}));
 const publicHost={uid:'host',fullName:'Real Host',bio:app.bio,regionId:'maan',photoData:'',publicPhone:'',verified:true,verifiedAt:serverTimestamp()};
 await no(setDoc(doc(imposter,'hosts','host'),publicHost));await no(setDoc(doc(host,'hosts','host'),publicHost));await yes(setDoc(doc(admin,'hosts','host'),publicHost));await yes(getDoc(doc(anon,'hosts','host')));await yes(updateDoc(doc(admin,'hostApplications','host'),{status:'approved',updatedAt:serverTimestamp()}));
 const experience={hostUid:'host',titleAr:'تجربة حقيقية',titleEn:'Actual local experience',descriptionAr:'تجربة محلية فعلية مع شرح تفاصيل النشاط وتعليمات السلامة ومكان اللقاء والمتطلبات الخاصة.',descriptionEn:'Actual local experience, meeting details, activity description and safety requirements are explained.',category:'tour',placeId:'petra',regionId:'maan',priceCents:2500,duration:60,photoData:'',communityBps:1000,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};
 await yes(setDoc(doc(host,'experiences','exp'),experience));await no(getDoc(doc(anon,'experiences','exp')));await no(updateDoc(doc(host,'experiences','exp'),{status:'approved',updatedAt:serverTimestamp()}));await yes(updateDoc(doc(admin,'experiences','exp'),{status:'approved',updatedAt:serverTimestamp()}));await yes(setDoc(doc(host,'experiences','new-place'),{...experience,placeId:'umm-jimal',regionId:'mafraq'}));await no(setDoc(doc(host,'experiences','wrong-region'),{...experience,placeId:'umm-jimal',regionId:'maan'}));await yes(getDocs(query(collection(anon,'experiences'),where('status','==','approved'))));await no(getDocs(collection(anon,'experiences')));
 const slot={experienceId:'exp',hostUid:'host',regionId:'maan',titleAr:experience.titleAr,titleEn:experience.titleEn,capacity:1,booked:0,priceCents:2500,communityBps:1000,startAt:Timestamp.fromMillis(Date.now()+96*3600000),endAt:Timestamp.fromMillis(Date.now()+97*3600000),open:true,lastBookingId:''};
 // Use exact duration to avoid clock drift.
 slot.endAt=Timestamp.fromMillis(slot.startAt.toMillis()+60*60000);
 await yes(setDoc(doc(host,'slots','slot'),slot));await no(updateDoc(doc(alice,'slots','slot'),{booked:1,lastBookingId:'fake'}));await no(updateDoc(doc(host,'slots','slot'),{capacity:999}));await no(updateDoc(doc(host,'slots','slot'),{priceCents:1}));
 function booking(uid,s=slot,slotId='slot'){return {uid,hostUid:'host',experienceId:'exp',slotId,travelerName:'Actual Traveler',guests:1,totalCents:s.priceCents,communityCents:250,hostCents:2250,status:'confirmed',paymentMethod:'cash',hostPaid:false,travelerPaid:false,startAt:s.startAt,endAt:s.endAt,titleAr:s.titleAr,titleEn:s.titleEn,regionId:s.regionId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};}
 async function reserve(db,uid,slotId='slot'){const bid=uid+'_'+slotId;return runTransaction(db,async tx=>{const r=doc(db,'slots',slotId);const s=(await tx.get(r)).data();await tx.get(doc(db,'bookings',bid));tx.set(doc(db,'bookings',bid),booking(uid,s,slotId));tx.update(r,{booked:s.booked+1,lastBookingId:bid});});}
 await no(setDoc(doc(alice,'bookings','alice_slot'),booking('alice')));
 const results=await Promise.allSettled([reserve(alice,'alice'),reserve(bob,'bob')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1,'exactly one user gets last seat');checks++;
 const winner=results[0].status==='fulfilled'?'alice':'bob',winnerDb=winner==='alice'?alice:bob,loserDb=winner==='alice'?bob:alice;
 const bid=winner+'_slot';await no(getDoc(doc(loserDb,'bookings',bid)));await no(updateDoc(doc(winnerDb,'bookings',bid),{totalCents:1,updatedAt:serverTimestamp()}));await no(updateDoc(doc(winnerDb,'bookings',bid),{hostPaid:true,updatedAt:serverTimestamp()}));await no(updateDoc(doc(winnerDb,'bookings',bid),{travelerPaid:true,updatedAt:serverTimestamp()}));await no(updateDoc(doc(winnerDb,'bookings',bid),{status:'cancelled',cancelledBy:winner,updatedAt:serverTimestamp()}));
 const batch=writeBatch(winnerDb);batch.update(doc(winnerDb,'bookings',bid),{status:'cancelled',cancelledBy:winner,updatedAt:serverTimestamp()});batch.update(doc(winnerDb,'slots','slot'),{booked:0,lastBookingId:bid});await yes(batch.commit());assert.equal((await getDoc(doc(host,'slots','slot'))).data().booked,0);checks++;
 await no(reserve(winnerDb,winner));await yes(reserve(loserDb,winner==='alice'?'bob':'alice'));
 const trip={uid:'alice',name:'Private planned trip',startDate:'2026-12-10',days:3,stops:[],status:'planned',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await yes(setDoc(doc(alice,'trips','trip'),trip));await no(getDoc(doc(bob,'trips','trip')));await no(getDoc(doc(anon,'trips','trip')));await no(updateDoc(doc(bob,'trips','trip'),{name:'hacked',updatedAt:serverTimestamp()}));await yes(updateDoc(doc(alice,'trips','trip'),{status:'completed',updatedAt:serverTimestamp()}));
 // Controlled fixtures for past visits and cancellation deadline.
 const pastSlot={...slot,startAt:Timestamp.fromMillis(Date.now()-3*3600000),endAt:Timestamp.fromMillis(Date.now()-2*3600000),booked:1,lastBookingId:'alice_past'};
 const soonSlot={...slot,startAt:Timestamp.fromMillis(Date.now()+2*3600000),endAt:Timestamp.fromMillis(Date.now()+3*3600000),booked:1,lastBookingId:'alice_soon'};
 await env.withSecurityRulesDisabled(async ctx=>{const d=ctx.firestore();await setDoc(doc(d,'slots','past'),pastSlot);await setDoc(doc(d,'bookings','alice_past'),booking('alice',pastSlot,'past'));await setDoc(doc(d,'slots','soon'),soonSlot);await setDoc(doc(d,'bookings','alice_soon'),booking('alice',soonSlot,'soon'));});
 const review={uid:'alice',hostUid:'host',experienceId:'exp',bookingId:'alice_past',rating:5,text:'Actual review after the completed visit.',createdAt:serverTimestamp()};await no(setDoc(doc(alice,'reviews','alice_past'),review));await no(updateDoc(doc(alice,'bookings','alice_past'),{hostPaid:true,updatedAt:serverTimestamp()}));await yes(updateDoc(doc(alice,'bookings','alice_past'),{travelerPaid:true,updatedAt:serverTimestamp()}));await no(setDoc(doc(alice,'reviews','alice_past'),review));await yes(updateDoc(doc(host,'bookings','alice_past'),{hostPaid:true,updatedAt:serverTimestamp()}));await yes(setDoc(doc(alice,'reviews','alice_past'),review));await no(setDoc(doc(alice,'reviews','alice_past'),{...review,rating:1}));await yes(getDocs(collection(anon,'reviews')));
 const cancel=writeBatch(alice);cancel.update(doc(alice,'bookings','alice_soon'),{status:'cancelled',cancelledBy:'alice',updatedAt:serverTimestamp()});cancel.update(doc(alice,'slots','soon'),{booked:0,lastBookingId:'alice_soon'});await no(cancel.commit());
 const hostCancel=writeBatch(host);hostCancel.update(doc(host,'bookings','alice_soon'),{status:'cancelled',cancelledBy:'host',updatedAt:serverTimestamp()});hostCancel.update(doc(host,'slots','soon'),{booked:0,lastBookingId:'alice_soon'});await yes(hostCancel.commit());
 const goal={titleAr:'مشروع مجتمعي حقيقي',titleEn:'Real community project',descriptionAr:'هدف متفق عليه مع المستفيد لدعم مشروع محلي فعلي موثق.',descriptionEn:'An agreed project with a beneficiary and reviewed funding needs.',regionId:'maan',targetCents:100000,published:true,createdAt:serverTimestamp()};await no(setDoc(doc(host,'goals','goal'),goal));await yes(setDoc(doc(admin,'goals','goal'),goal));
 const receipt={bookingId:'alice_past',goalId:'goal',amountCents:250,status:'received',createdAt:serverTimestamp()};await no(setDoc(doc(admin,'contributions','alice_past'),receipt));await yes(setDoc(doc(admin,'receiptEvidence','alice_past'),{reference:'BANK-RECEIPT-QA',recordedBy:'admin',createdAt:serverTimestamp()}));await no(getDoc(doc(alice,'receiptEvidence','alice_past')));await no(setDoc(doc(admin,'contributions','alice_past'),{...receipt,amountCents:999}));await no(setDoc(doc(alice,'contributions','alice_past'),receipt));await yes(setDoc(doc(admin,'contributions','alice_past'),receipt));await yes(getDocs(query(collection(anon,'contributions'),where('status','==','received'))));await no(updateDoc(doc(admin,'contributions','alice_past'),{amountCents:999}));
 console.log(`PASS ${checks} marketplace permission/validation checks including concurrent last-seat booking, cancellation, cash, reviews, private identity and receipts`);await env.cleanup();
})().catch(err=>{console.error(err);process.exitCode=1;});
